### ISSUE TITLE
Redesign home page and Footer

### ISSUE THREAD

**Issue by AKSHATH99** [rudalkunwar/recipe-app#15]
I would like to work on redesigning the Home page , more specifically the "share your recipe section " and "start your cooking journey section" . 
There aren't any much styling done currently. Adding images and improving spacing would improve the UI 

Footer section need to be redesigned to include social media links and  also add up  a contact us section 

Do assign me this issue under hacktoberfest 

Thank you

**Comment by rudalkunwar** [comment]
approved
