### ISSUE TITLE
I can add animation on the cards that appear on search. Whenever someone hovers on it, it can grow in size or have a shadow. Basically, animation on hover.

### ISSUE THREAD

**Issue by Unnati2603** [rudalkunwar/recipe-app#16]

**Comment by Unnati2603** [comment]
If you want this, please assign it to me. @rudalkunwar

**Comment by rudalkunwar** [comment]
okey head on

**Comment by Unnati2603** [comment]
@rudalkunwar   I have added the effects. I hope you are satisfied with the results :D. If you are then please tell, I will create a pull request.
Or do you want to change something? 
Here is a side by side comparison.

Original
![image](https://github.com/user-attachments/assets/260c2565-7c46-4aa0-9162-9fed0e2d46e4)

New
![image](https://github.com/user-attachments/assets/9265b21f-6f60-45c1-81fa-8ec3d9a6fc3a)

**Comment by Unnati2603** [comment]
https://github.com/user-attachments/assets/f1686688-4215-4fda-99e6-7772d3b20532

a video of the same @rudalkunwar

**Comment by rudalkunwar** [comment]
nice work!
