### ISSUE TITLE
Feature : Create a form-page to submit recipe 

### ISSUE THREAD

**Issue by AKSHATH99** [rudalkunwar/recipe-app#18]
Currently , the home page has a call to action button to submit recipe . I would like to work on building form-page for the same 

Thank you

**Comment by rudalkunwar** [comment]
okey

**Comment by Kirti-Pant** [comment]
@rudalkunwar can you assign me this issue?

**Comment by rudalkunwar** [comment]
@Kirti-Pant , pr is already done by @AKSHATH99 and is on review. You can contribute on other issue by creating one.

**Comment by Kirti-Pant** [comment]
okey
